apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: god-role
  namespace: default

rules:
- apiGroups:
  - "apps"
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["samplecontroller.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: god-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: god-role
subjects:
- kind: ServiceAccount
  name: scale-account
  namespace: default